name: Source mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '20 12 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env: 
      is_enabled: ${{ secrets.IS_ENABLED }} 
    steps:
      - name: Check if running is enabled
        if: ${{ env.is_enabled == '' }}
        run: |-
          echo "Running is not enabled, script will terminate"
          exit 0
      - uses: actions/checkout@v4
      - name: Fetch latest data
        run: |-
          wget --no-verbose ${{ secrets.SOURCE_FULL }} -O guide.xml
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push