name: Source mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '20 12 * * *'

jobs:
  check-status:
    runs-on: ubuntu-latest
    outputs:
      is-enabled: ${{ steps.is-enabled.outputs.defined }}
    steps:
      - name: Check for Secret availability
        id: is-enabled
        shell: bash
        run: |
          if [ "${{ secrets.IS_ENABLED }}" != '' ]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi


  deploy:
    runs-on: ubuntu-latest
    needs: [check-status]
    permissions:
      contents: write
    if: needs.check-status.outputs.is-enabled == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Fetch latest data
        run: |-
          wget --no-verbose ${{ secrets.SOURCE_FULL }} -O guide.xml
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push