name: Source mirror

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

  schedule:
    - cron: '30 14 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      COMMIT_MESSAGE: Update
      COMMIT_AUTHOR: Continuous Integration
    steps:
      - uses: actions/checkout@v3

      # Commit and push all changed files.
      - name: Update
        run: |
          wget --no-verbose ${{ secrets.SOURCE_FULL }} -O guide.xml
          git config --global user.name "${{ env.COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add .
          git commit -m "${{ env.COMMIT_MESSAGE }}"
          git push